### PR TITLE
docs: updating the vignette

### LINKED ISSUE #99: Add vignette for binned maximum likelihood estimation
- General derivation of MLE for binned data on underlying continuous distribution (Expand on [this CV answer](https://stats.stackexchange.com/questions/60256/standard-deviation-of-binned-observations/68238#68238))
-  Sample moment calculation and derivations (mean, sd, skewness)

Basic code example:

``` r
library(HistogramZoo);
#> Loading required package: extraDistr
set.seed(100);
x <- rnorm(1000, sd = 5);
bin.x <- observations_to_histogram(x);

bin_log_likelihood(
  theta = c(0, 4),
  cdf = pnorm,
  counts = bin.x$histogram_data,
  bin_lower = bin.x$interval_start,
  bin_upper = bin.x$interval_end
  );
#> [1] 3137.2

dist_optim <- DEoptim::DEoptim(
  fn = bin_log_likelihood,
  cdf = pnorm,
  counts = bin.x$histogram_data,
  bin_lower = bin.x$interval_start,
  bin_upper = bin.x$interval_end,
  lower = c(min(bin.x$interval_start), 0.01),
  upper = c(max(bin.x$interval_end), 10),
  control = list(
    trace = FALSE,
    itermax = 500
    )
  );
print(dist_optim$optim$bestmem);
#>       par1       par2 
#> 0.08099956 5.15636585
```

<sup>Created on 2023-04-04 with [reprex v2.0.2](https://reprex.tidyverse.org)</sup>

### LINKED ISSUE #114: Update vignette with latest changes
* MLE methods
* Parameter estimation
* Histogram plotting
* GenomicHistogram updates
  * consecutive bins
  * introns
 * S3 methods

### PR DESCRIPTION
**Pull request by helen-zhu**
# Description
Vignette update includes the following:
* MLE method for distribution fitting
* Summary statistic estimation
 * Summarize_results → additional columns 
* `create_histogram` plotting
* updates to the GenomicHistogram and Histogram class
 * consecutive bins
 * introns
* Correcting examples to use S3 methods on Histogram/GenomicHistogram objects
 
Need to update vignette with the following before merging PR:
* merge the truncated_gamma_shifted branch PR - currently, the gamma_flipped example isn't correct
* Uncomment the code in the summarize_results section to allow for empirical summary statistic estimation

### Closes #99, Closes #114 

# Checklist

- [X] This PR does NOT contain [PHI](https://ohrpp.research.ucla.edu/hipaa/) or germline genetic data.  A repo may need to be deleted if such data is uploaded. Disclosing PHI is a [major problem](https://healthitsecurity.com/news/ucla-health-reaches-7.5m-settlement-over-2015-breach-of-4.5m).
- [X] This PR does NOT contain molecular files, compressed files, output files such as images (*e.g.* `.png`, .`jpeg`), `.pdf`, `.RData`, `.xlsx`, `.doc`, `.ppt`, or other non-plain-text files.  To automatically exclude such files using a [.gitignore](https://docs.github.com/en/get-started/getting-started-with-git/ignoring-files) file, see [here](https://github.com/uclahs-cds/template-base/blob/main/.gitignore) for example.
- [X] I have read the [code review guidelines](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Guidelines) and the [code review best practice on GitHub check-list](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List).
- [X] I have set up or verified the `main` branch protection rule following the [github standards](https://confluence.mednet.ucla.edu/pages/viewpage.action?spaceKey=BOUTROSLAB&title=GitHub+Standards#GitHubStandards-Branchprotectionrule) before opening this pull request.
- [X] The name of the branch is meaningful and well formatted following the [standards](https://confluence.mednet.ucla.edu/display/BOUTROSLAB/Code+Review+Best+Practice+on+GitHub+-+Check+List), using [AD_username (or 5 letters of AD if AD is too long)]-[brief_description_of_branch].
- [X] I have added the major changes included in this pull request to the `CHANGELOG.md` under the next release version or unreleased, and updated the date.

### CODE REVIEW

**Comment by helen-zhu** [comment]
@stefaneng I think this branched off the S3 methods branch so there are some duplicated commits even after merging main - but this is the only one. Can be reviewed last if you prefer.

**Comment by helen-zhu** [comment]
> @stefaneng I think this branched off the S3 methods branch so there are some duplicated commits even after merging main - but this is the only one. Can be reviewed last if you prefer.

Merged S3 methods --> main --> vignette branch, should be vignette commits only now.

**Review by stefaneng — APPROVED** [review]
@helen-zhu I added formulas for the histogram metrics and changed a bit of the text. Everything else looks good so feel free to merge if you are okay with the changes.

**Comment by helen-zhu** [comment]
> @helen-zhu I added formulas for the histogram metrics and changed a bit of the text. Everything else looks good so feel free to merge if you are okay with the changes.

Thanks for the input @stefaneng! I noticed you took out the mle estimation - do you think we don't need it or that we should add it back in more detail in the future?

**Comment by stefaneng** [comment]
> > @helen-zhu I added formulas for the histogram metrics and changed a bit of the text. Everything else looks good so feel free to merge if you are okay with the changes.
> 
> Thanks for the input @stefaneng! I noticed you took out the mle estimation - do you think we don't need it or that we should add it back in more detail in the future?

Oh, I meant to add it back good catch. I just wanted to pull it out of the "Metric" section and into a separate section.

**Pull request merged**
